### ISSUE TITLE
Segment information inconsistencies (?)

### ISSUE THREAD

**Issue by mikessh** [repseqio/library#26]
**Mouse**
* Actually a variable gene: ``IGLC1*00``
* Named as ``TCR?-V`` instead of ``TR?V``: ``TCRG-V3*00``, ``TCRG-V1*00``, ``TCRG-V7*00``, ``TCRG-V5*00``, ``TCRG-V6*00``, ``TCRG-V4*00``

**Rat**
* Not assigned to both TRA and TRD; inconsistent naming (dash notation): ``TRAV6-7-DV9*00-1``, ``TRAV6-7-DV9*00-2``, ``TRAV21/DV12*00``
* Recorded as TRA only ``TRDV1*00``, ``TRDV2*00``

Please check me

**Comment by dbolotin** [comment]
??

> Actually a variable gene: IGLC1*00

**Comment by dbolotin** [comment]
Waiting for @mikessh 's clarifications on IGLC1*00, other things fixed.
