### ISSUE TITLE
Packaging for Debian - License? Or just not package it separately?

### ISSUE THREAD

**Issue by smoe** [repseqio/library#29]
Hello,

for packaging MiXCR for Debian I came across repseqio as a dependency, which again has this library as a git submodule. And here again is a build script that refers to repseq - should this repository appear as its very own package in the first place? And what is its license?

Many thanks!

Steffen

**Comment by PoslavskySV** [comment]
Dear Steffen,

The library is open sourced, licensed under CC BY, we'll attach License file to the repo.

On the other hand MiXCR is a commercial software. It is strongly prohibited to use MiXCR without obtaining the license from MiLaboratory LLC. The exception is made only for academic users. We do not allow to include MiXCR distribution in existing package management systems and repositories. There is officially supported Homebrew formula `milaboratory/all/mixcr`.

With best wishes,
Stanislav

**Comment by smoe** [comment]
Dear Stanislav,

Thank you for your kind reply. Hm. Right. "academic only" is not so problematic since we have the "non-free" part of Debian. But "non-redistributable" kills MiXCR packaging for Debian, obviously. To be more exact, it does not kill the packaging itself but the upload to the Debian servers. Should you ever decide to distribute a Debian(+Ubuntu+Mint+Raspbian+...) package yourselves from your own repository then please send me/Debian Med a ping if you need any help.

Thank you for your work!
Steffen

**Comment by PoslavskySV** [comment]
Dear Steffen,

thank you! We will think about "non-free" repo option.

Cheers,
Stanislav
